import { TEAL, TEAL_LIGHT, TEAL_MID, ACCENT, TEXT, MUTED, BORDER, BG, WHITE } from "../theme.js";

const s = {

  stepProgress: { color: MUTED, fontSize: 11, fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 12 },
  roleGrid: { display: "flex", flexDirection: "column", gap: 10 },
  roleCard: { background: WHITE, border: `1.5px solid #e8e8e8`, borderRadius: 10, padding: "16px 20px", cursor: "pointer", textAlign: "left", fontFamily: "inherit" },
  roleCardActive: { background: WHITE, border: `2px solid ${TEAL}` },
  roleCardTitle: { color: TEXT, fontSize: 14, fontWeight: 600, marginBottom: 3 },
  roleCardSub: { color: MUTED, fontSize: 12, lineHeight: 1.5 },

  introTabBar: { display: "flex", gap: 4, borderBottom: `1px solid ${BORDER}`, marginBottom: 20, marginTop: 4 },
  introTabBtn: { background: "transparent", border: "none", borderBottom: "2px solid transparent", padding: "8px 16px", fontSize: 12, fontWeight: 500, color: MUTED, cursor: "pointer", fontFamily: "inherit", marginBottom: -1 },
  introTabBtnActive: { color: TEAL, borderBottomColor: TEAL, fontWeight: 700 },
  introTabContent: { },
  // ── LAYOUT ───────────────────────────────────────────────────
  siteWrapper: { minHeight: "100vh", background: BG, fontFamily: "'Lato', 'Helvetica Neue', Arial, sans-serif" },

  // ── STICKY HEADER ────────────────────────────────────────────
  stickyHeader: { position: "sticky", top: 0, zIndex: 50, background: "rgba(255,255,255,0.95)", backdropFilter: "blur(8px)", borderBottom: `1px solid ${BORDER}`, boxShadow: "0 1px 0 rgba(42,122,106,0.06)" },
  headerInner: { maxWidth: 1200, margin: "0 auto", padding: "0 40px", height: 58, display: "flex", alignItems: "center", gap: 14 },
  navCityBadge: { background: TEAL_LIGHT, color: TEAL, border: `1px solid ${TEAL_MID}`, borderRadius: 20, padding: "3px 10px", fontSize: 11, fontWeight: 600 },
  navRestartBtn: { background: "transparent", color: MUTED, border: `1px solid ${BORDER}`, borderRadius: 6, padding: "5px 12px", fontSize: 12, cursor: "pointer", fontFamily: "inherit" },
  helpBtn: { width: 28, height: 28, borderRadius: "50%", border: `1px solid ${BORDER}`, background: WHITE, color: MUTED, fontSize: 13, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "inherit" },
  langToggle: { display: "flex", border: `1px solid ${BORDER}`, borderRadius: 6, overflow: "hidden" },
  langBtn: { background: WHITE, color: MUTED, border: "none", padding: "5px 10px", fontSize: 11, fontWeight: 600, cursor: "pointer", letterSpacing: "0.05em" },
  langBtnActive: { background: TEAL, color: WHITE },

  // ── HERO ─────────────────────────────────────────────────────
  heroSection: { background: WHITE, borderBottom: `1px solid ${BORDER}`, padding: "72px 40px 64px" },
  heroInner: { maxWidth: 700, margin: "0 auto", textAlign: "center" },
  heroBadge: {
    display: "inline-block",
    background: "rgba(255,255,255,0.12)",
    color: "#fff",
    border: "1px solid rgba(255,255,255,0.3)",
    borderRadius: 20,
    padding: "5px 14px",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    marginBottom: 20
  },
  heroTitle: {
    color: "#fff",
    fontSize: "clamp(28px, 4vw, 48px)",
    fontWeight: 800,
    lineHeight: 1.15,
    margin: "0 0 20px",
    letterSpacing: "-0.02em"
  },
  heroSub: { color: MUTED, fontSize: 13, lineHeight: 1.7, margin: "0 0 36px", maxWidth: 560, marginLeft: "auto", marginRight: "auto" },
  heroStats: { display: "flex", alignItems: "center", justifyContent: "center", gap: 0, marginBottom: 36, background: TEAL_LIGHT, borderRadius: 12, padding: "16px 32px", border: `1px solid ${TEAL_MID}`, display: "inline-flex" },
  heroStat: { display: "flex", flexDirection: "column", alignItems: "center", padding: "0 24px" },
  heroStatNum: { color: TEAL, fontSize: 22, fontWeight: 800, lineHeight: 1 },
  heroStatLabel: { color: MUTED, fontSize: 11, marginTop: 4, letterSpacing: "0.05em" },
  heroStatDiv: { width: 1, height: 36, background: TEAL_MID },
  heroScrollBtn: { display: "inline-block", background: TEAL, color: WHITE, borderRadius: 8, padding: "12px 28px", fontWeight: 600, fontSize: 14, textDecoration: "none", letterSpacing: "0.01em" },

  // ── TOOL SECTION ─────────────────────────────────────────────
  toolSection: { padding: "48px 40px 64px", display: "flex", flexDirection: "column", alignItems: "center" },

  // ── CARD ─────────────────────────────────────────────────────
  card: { background: WHITE, border: `1px solid ${BORDER}`, borderRadius: 12, padding: "36px 40px", maxWidth: 780, width: "100%", boxShadow: "0 2px 20px rgba(42,122,106,0.08)" },
  header: { display: "flex", alignItems: "center", gap: 14, marginBottom: 28, paddingBottom: 20, borderBottom: `1px solid ${BORDER}` },
  logoImg: { height: 30, objectFit: "contain" },
  headerDiv: { width: 1, height: 22, background: BORDER },
  headerSub: { color: MUTED, fontSize: 11, letterSpacing: "0.1em", textTransform: "uppercase", fontWeight: 500 },
  banner: { display: "flex", alignItems: "center", gap: 8, background: TEAL_LIGHT, border: `1px solid ${TEAL_MID}`, borderRadius: 6, padding: "7px 12px", marginBottom: 12, color: TEAL, fontSize: 12, fontWeight: 500 },
  bannerDot: { display: "inline-block", width: 7, height: 7, borderRadius: "50%", background: ACCENT, flexShrink: 0 },
  sourceNote: { color: MUTED, fontSize: 11, lineHeight: 1.5, fontStyle: "italic" },
  h1: { color: TEXT, fontSize: 17, fontWeight: 700, margin: "0 0 12px", lineHeight: 1.35 },
  h2: { color: TEXT, fontSize: 16, fontWeight: 700, margin: "6px 0 4px" },
  desc: { color: MUTED, fontSize: 12, lineHeight: 1.7, margin: "0 0 12px" },
  desc2: { color: MUTED, fontSize: 11, margin: 0 },
  chips: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 24 },
  chip: { background: TEAL_LIGHT, color: TEAL, border: `1px solid ${TEAL_MID}`, borderRadius: 20, padding: "5px 12px", fontSize: 12, fontWeight: 500 },
  label: { display: "block", color: TEXT, fontSize: 12, fontWeight: 600, marginBottom: 6 },
  input: { width: "100%", border: `1px solid ${BORDER}`, borderRadius: 7, padding: "10px 14px", color: TEXT, fontSize: 14, outline: "none", boxSizing: "border-box", background: WHITE, fontFamily: "inherit", marginBottom: 20 },
  select: { width: "100%", border: `1px solid ${BORDER}`, borderRadius: 7, padding: "10px 14px", color: TEXT, fontSize: 14, outline: "none", boxSizing: "border-box", background: WHITE, fontFamily: "inherit", marginBottom: 20, cursor: "pointer", appearance: "auto" },
  btnPrimary: { display: "block", width: "100%", background: TEAL, color: WHITE, border: "none", borderRadius: 7, padding: "12px 24px", fontWeight: 600, fontSize: 13, fontFamily: "inherit", cursor: "pointer" },
  btnOutline: { background: WHITE, color: TEAL, border: `1px solid ${TEAL_MID}`, borderRadius: 7, padding: "10px 20px", fontWeight: 600, fontSize: 13, cursor: "pointer", fontFamily: "inherit" },
  btnSkip: { background: "transparent", color: MUTED, border: `1px dashed ${BORDER}`, borderRadius: 7, padding: "8px 14px", fontWeight: 500, fontSize: 12, cursor: "pointer", fontFamily: "inherit", marginTop: 8, width: "100%", textAlign: "center" },
  btnRestart: { background: "transparent", color: MUTED, border: "none", padding: "8px 4px", fontSize: 12, cursor: "pointer", fontFamily: "inherit", textDecoration: "underline", textUnderlineOffset: 2 },
  hint: { textAlign: "center", color: MUTED, fontSize: 12, marginTop: 12 },
  progressBar: { height: 5, background: TEAL_LIGHT, borderRadius: 3, marginBottom: 20 },
  progressFill: { height: "100%", background: TEAL, borderRadius: 3, transition: "width 0.3s" },
  tabRow: { display: "flex", alignItems: "center", gap: 6, marginBottom: 24, flexWrap: "wrap" },
  tab: { background: TEAL_LIGHT, color: MUTED, border: `1px solid ${BORDER}`, borderRadius: 8, width: 38, height: 38, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", position: "relative" },
  tabActive: { background: TEAL, border: `1px solid ${TEAL}` },
  tabDone: { border: `1px solid ${TEAL_MID}`, opacity: 0.65 },
  checkPin: { position: "absolute", top: -5, right: -5, fontSize: 8, background: ACCENT, color: WHITE, borderRadius: "50%", width: 14, height: 14, display: "flex", alignItems: "center", justifyContent: "center" },
  tabLabel: { color: TEXT, fontSize: 14, fontWeight: 600, marginLeft: 6 },
  qBlock: { background: WHITE, borderRadius: 10, padding: "16px 20px", marginBottom: 10, border: `1px solid ${BORDER}` },
  qText: { color: TEXT, fontSize: 13, lineHeight: 1.6, margin: "0 0 12px", fontWeight: 500 },
  qNum: { color: TEAL, fontWeight: 700, marginRight: 4 },
  opt: { background: WHITE, color: TEXT, border: `1px solid #e0e0e0`, borderRadius: 7, padding: "7px 16px", fontSize: 12, cursor: "pointer", fontFamily: "inherit", fontWeight: 600, outline: "none" },
  optSel: { background: TEAL_LIGHT, border: `2px solid ${TEAL}`, color: TEAL },
  radio: { display: "none" },
  radioSel: { display: "none" },
  resultsTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", margin: "0 0 24px" },
  cityPill: { display: "inline-block", background: TEAL_LIGHT, color: TEAL, border: `1px solid ${TEAL_MID}`, borderRadius: 20, padding: "4px 12px", fontSize: 11, fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase" },
  totalLbl: { color: MUTED, fontSize: 11, marginTop: 4 },
  badge: { display: "inline-block", borderRadius: 20, padding: "4px 12px", fontSize: 12, fontWeight: 700, marginTop: 4 },
  badgeSm: { display: "inline-block", borderRadius: 20, padding: "3px 9px", fontSize: 11, fontWeight: 700, marginTop: 4 },
  grid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, marginBottom: 20 },
  catCard: { background: WHITE, border: `1px solid ${BORDER}`, borderRadius: 10, padding: "16px" },
  catHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  catToggle: { marginTop: 10, background: "transparent", border: "none", color: MUTED, fontSize: 11, cursor: "pointer", fontFamily: "inherit", padding: "4px 0", textAlign: "left" },
  catName: { color: TEXT, fontSize: 13, fontWeight: 700, margin: "4px 0 2px" },
  catScore: { color: MUTED, fontSize: 11, marginBottom: 4 },
  sep: { height: 1, background: BORDER, margin: "10px 0" },
  aQ: { display: "block", color: MUTED, fontSize: 11, lineHeight: 1.4 },
  aA: { display: "block", color: TEXT, fontSize: 11, fontWeight: 600, marginTop: 1 },
  methodNote: { background: TEAL_LIGHT, border: `1px solid ${TEAL_MID}`, borderRadius: 7, padding: "12px 16px", color: MUTED, fontSize: 12, lineHeight: 1.6, marginBottom: 16 },

  // ── INTRO TWO-COLUMN ─────────────────────────────────────────
  introWrap: { display: "flex", gap: 24, alignItems: "flex-start", maxWidth: 1100, width: "100%", position: "relative" },

  // ── TILES PANEL ──────────────────────────────────────────────
  tilesPanel: { width: 220, flexShrink: 0, background: WHITE, border: `1px solid ${BORDER}`, borderRadius: 12, padding: "18px 16px", boxShadow: "0 2px 12px rgba(42,122,106,0.07)" },
  tilesPanelTitle: { color: TEXT, fontSize: 12, fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 2 },
  tilesPanelSub: { color: MUTED, fontSize: 11, marginBottom: 14 },
  tileGroup: { marginBottom: 12 },
  tileGroupLabel: { fontSize: 10, fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 5 },
  tileRow: { display: "flex", flexWrap: "wrap", gap: 4 },
  tile: { border: "1.5px solid", borderRadius: 5, padding: "3px 6px", fontSize: 11, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },

  // ── TILE MODAL ───────────────────────────────────────────────
  tileModal: { position: "fixed", inset: 0, zIndex: 100, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(0,0,0,0.25)" },
  tileModalBox: { background: WHITE, borderRadius: 10, padding: "20px 24px", maxWidth: 340, width: "90%", boxShadow: "0 8px 32px rgba(0,0,0,0.18)" },
  tileModalCode: { fontSize: 22, fontWeight: 800, letterSpacing: "0.04em" },
  tileModalClose: { background: "transparent", border: "none", color: MUTED, fontSize: 16, cursor: "pointer", padding: 0 },
  tileModalName: { color: TEXT, fontSize: 14, fontWeight: 700, marginBottom: 8 },
  tileModalDesc: { color: MUTED, fontSize: 13, lineHeight: 1.6, margin: 0 },

  // ── REVIEW ───────────────────────────────────────────────────
  reviewCatBlock: { marginBottom: 20 },
  reviewCatHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8, paddingBottom: 6, borderBottom: `1px solid ${BORDER}` },
  reviewCatLabel: { color: TEXT, fontSize: 12, fontWeight: 700, letterSpacing: "0.06em", textTransform: "uppercase" },
  reviewEditBtn: { background: "transparent", color: TEAL, border: `1px solid ${TEAL_MID}`, borderRadius: 5, padding: "3px 10px", fontSize: 11, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
  reviewRow: { display: "flex", alignItems: "flex-start", gap: 10, padding: "8px 10px", borderRadius: 6, border: `1px solid ${BORDER}`, marginBottom: 5 },
  reviewQNum: { color: MUTED, fontSize: 11, fontWeight: 600, flexShrink: 0, paddingTop: 2 },
  reviewQText: { color: TEXT, fontSize: 12, lineHeight: 1.5 },
  reviewAns: { fontSize: 11, fontWeight: 600, borderRadius: 10, padding: "2px 10px", flexShrink: 0, whiteSpace: "nowrap" },

  // ── SUGGESTED MEASURES ───────────────────────────────────────
  suggestTitle: { color: TEXT, fontSize: 13, fontWeight: 700, marginBottom: 4 },
  suggestSub: { color: MUTED, fontSize: 11, marginBottom: 12 },
  suggestGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  suggestCard: { background: WHITE, border: `1px solid ${BORDER}`, borderRadius: 10, padding: "14px 16px" },
  suggestCardCode: { display: "inline-block", color: WHITE, fontSize: 11, fontWeight: 800, borderRadius: 5, padding: "2px 8px", letterSpacing: "0.06em", flexShrink: 0 },
  suggestCardName: { color: TEXT, fontSize: 12, fontWeight: 700, lineHeight: 1.3 },
  suggestCardDesc: { color: MUTED, fontSize: 11, lineHeight: 1.5, margin: "0 0 10px" },
  suggestCardDivider: { height: 1, background: BORDER, marginBottom: 8 },
  suggestCardRow: { display: "flex", gap: 8, marginBottom: 5, alignItems: "flex-start" },
  suggestCardRowLabel: { fontSize: 10, fontWeight: 700, minWidth: 110, flexShrink: 0, paddingTop: 1 },
  suggestCardRowVal: { color: TEXT, fontSize: 10, lineHeight: 1.4 },

  // ── OSM PANEL ────────────────────────────────────────────────
  osmPanel: { marginTop: 16, background: "#f0fbfb", border: "1px solid #b2e4e4", borderRadius: 8, padding: "14px 16px" },
  osmPanelTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  osmPanelTitle: { color: "#0a6060", fontSize: 12, fontWeight: 700, marginBottom: 2 },
  osmPanelSub: { color: MUTED, fontSize: 11, lineHeight: 1.4 },
  osmBtn: { background: "#0a9ea0", color: WHITE, border: "none", borderRadius: 6, padding: "7px 14px", fontSize: 12, fontWeight: 600, fontFamily: "inherit", flexShrink: 0 },
  osmResult: { marginTop: 12, paddingTop: 12, borderTop: "1px solid #b2e4e4" },
  osmResultTitle: { color: "#0a6060", fontSize: 11, fontWeight: 600, marginBottom: 8 },
  osmResultGrid: { display: "flex", flexDirection: "column", gap: 5 },
  osmResultRow: { display: "flex", alignItems: "center", gap: 8 },
  osmResultLabel: { color: TEXT, fontSize: 11, flex: 1 },
  osmResultVal: { color: MUTED, fontSize: 11 },
  osmResultScore: { fontSize: 10, fontWeight: 700, borderRadius: 10, padding: "2px 7px" },
  osmAttrib: { color: MUTED, fontSize: 10, marginTop: 8, fontStyle: "italic" },
  osmBadge: { display: "inline-block", background: "#0a9ea0", color: WHITE, fontSize: 9, fontWeight: 700, borderRadius: 4, padding: "1px 5px", marginLeft: 6, verticalAlign: "middle", letterSpacing: "0.04em" },

  // ── ONBOARDING ───────────────────────────────────────────────
  onboardOverlay: { position: "fixed", inset: 0, zIndex: 200, background: "rgba(15,30,25,0.6)", backdropFilter: "blur(4px)", display: "flex", alignItems: "center", justifyContent: "center", padding: "24px 16px" },
  onboardBox: { background: WHITE, borderRadius: 12, padding: "24px 32px", maxWidth: 700, width: "100%", boxShadow: "0 16px 48px rgba(0,0,0,0.2)", maxHeight: "85vh", overflowY: "auto" },
  onboardHeader: { display: "flex", alignItems: "center", gap: 12, marginBottom: 12, paddingBottom: 12, borderBottom: `1px solid ${BORDER}` },
  onboardHeaderDiv: { width: 1, height: 18, background: BORDER },
  onboardHeaderSub: { color: MUTED, fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase", fontWeight: 600 },
  onboardSub: { color: MUTED, fontSize: 12, lineHeight: 1.6, margin: "0 0 16px" },
  onboardGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 20 },
  onboardSectionTitle: { color: TEXT, fontSize: 10, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 10, paddingBottom: 6, borderBottom: `1px solid ${BORDER}` },
  onboardSection: { display: "flex", gap: 10, marginBottom: 10 },
  onboardNumBadge: { width: 18, height: 18, borderRadius: "50%", background: TEAL, color: WHITE, fontSize: 10, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 1 },
  onboardSecLabel: { color: TEXT, fontSize: 12, fontWeight: 600, marginBottom: 2 },
  onboardSecDesc: { color: MUTED, fontSize: 11, lineHeight: 1.5 },
  onboardCard: { background: "#f9fafb", border: `1px solid ${BORDER}`, borderRadius: 8, padding: "12px", borderTop: `3px solid ${TEAL}` },
  onboardCardCode: { display: "inline-block", background: TEAL, color: WHITE, fontSize: 11, fontWeight: 800, borderRadius: 4, padding: "2px 8px", marginBottom: 4, letterSpacing: "0.06em" },
  onboardCardTitle: { color: TEXT, fontSize: 12, fontWeight: 700, marginBottom: 8 },
  onboardCardDivider: { height: 1, background: BORDER, marginBottom: 8 },
  onboardCardRow: { display: "flex", gap: 6, marginBottom: 5, alignItems: "flex-start" },
  onboardCardRowLabel: { color: TEAL, fontSize: 10, fontWeight: 700, minWidth: 120, flexShrink: 0 },
  onboardCardRowDesc: { color: MUTED, fontSize: 10, lineHeight: 1.4 },
  onboardBtn: { width: "100%", background: TEAL, color: WHITE, border: "none", borderRadius: 7, padding: "10px 20px", fontWeight: 700, fontSize: 13, cursor: "pointer", fontFamily: "inherit", letterSpacing: "0.03em" },

  // ── CONTEXT SECTION ──────────────────────────────────────────
  contextSection: { background: WHITE, borderTop: `1px solid ${BORDER}`, padding: "72px 40px" },
  contextInner: { maxWidth: 680, margin: "0 auto" },
  contextTag: { display: "inline-block", background: TEAL_LIGHT, color: TEAL, border: `1px solid ${TEAL_MID}`, borderRadius: 20, padding: "4px 12px", fontSize: 10, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 16 },
  sectionTitle: { color: TEXT, fontSize: 20, fontWeight: 700, margin: "0 0 16px", letterSpacing: "-0.01em" },
  contextText: { color: MUTED, fontSize: 13, lineHeight: 1.8, margin: "0 0 24px" },
  contextLink: { color: TEAL, fontSize: 14, fontWeight: 600, textDecoration: "none", borderBottom: `1px solid ${TEAL_MID}`, paddingBottom: 2 },

  // ── FEEDBACK SECTION ─────────────────────────────────────────
  feedbackSection: { background: BG, borderTop: `1px solid ${BORDER}`, padding: "72px 40px" },
  feedbackInner: { maxWidth: 600, margin: "0 auto" },
  feedbackSub: { color: MUTED, fontSize: 12, lineHeight: 1.7, margin: "0 0 28px" },
  feedbackForm: { display: "flex", flexDirection: "column", gap: 12 },
  feedbackRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  feedbackInput: { border: `1px solid ${BORDER}`, borderRadius: 7, padding: "10px 14px", color: TEXT, fontSize: 13, outline: "none", background: WHITE, fontFamily: "inherit" },
  feedbackTextarea: { border: `1px solid ${BORDER}`, borderRadius: 7, padding: "10px 14px", color: TEXT, fontSize: 13, outline: "none", background: WHITE, fontFamily: "inherit", resize: "vertical" },
  feedbackSuccess: { background: TEAL_LIGHT, border: `1px solid ${TEAL_MID}`, borderRadius: 8, padding: "14px 18px", color: TEAL, fontSize: 14, fontWeight: 500 },

  // ── FOOTER ───────────────────────────────────────────────────
  siteFooter: { background: TEAL, padding: "48px 40px" },
  footerInner: { maxWidth: 900, margin: "0 auto", display: "flex", flexDirection: "column", alignItems: "center", gap: 12, textAlign: "center" },
  footerText: { color: "rgba(255,255,255,0.75)", fontSize: 13, margin: 0 },
  footerLink: { color: "rgba(255,255,255,0.6)", fontSize: 12, textDecoration: "none", borderBottom: "1px solid rgba(255,255,255,0.3)", paddingBottom: 2 },
};

export default s;